# Default configuration for ECDSA Audit System

# Core parameters
curve: "secp256k1"
default_num_regions: 10
default_region_size: 50

# Safety thresholds
betti_thresholds:
  beta_0: 1.0    # Expected value for β₀
  beta_1: 2.0    # Expected value for β₁
  beta_2: 1.0    # Expected value for β₂
gamma_threshold: 0.1     # Minimum acceptable damping coefficient
symmetry_threshold: 0.85 # Minimum acceptable symmetry score
spiral_threshold: 0.7    # Minimum acceptable spiral structure strength

# Parallel processing
max_workers: null        # null means use all available cores
chunk_size: 1

# Logging
log_level: "INFO"
log_file: null           # null means log to console

# Performance
cache_enabled: true
cache_size: 1000
timeout: 300             # seconds

# Visualization
visualization:
  output_dir: "visualizations"
  dpi: 300
  color_scheme: "blue_red"

# Report generation
report:
  template_dir: "templates"
  output_dir: "reports"
  default_format: "html"
